### ISSUE TITLE
Time

### ISSUE THREAD

**Issue by mormahr** [excitement-engineer/graphql-iso-date#8]
Could you implement the same formats (including the time ones) that you propose in graphql/graphql-js#557 ?

This is a good foundation and a good interim solution, but it only covers date (without timezone) not time.

Thanks in advance

**Comment by excitement-engineer** [comment]
Hey @mormahr. Unfortunately I am quite busy at the moment with work related stuff so I don't have the time in the next couple of weeks for getting to this. Hopefully we will be able to merge an experimental version of the Date/Time scalars in the graphql-js repo soon. If not, then I will definitely update this library with the full spectrum of Date/Time scalars so that it provides a comprehensive solution for modelling this in GraphQL!

**Comment by excitement-engineer** [comment]
Hey @mormahr. The library has been updated with new RFC 3339 compliants date/time scalars:) Let me know what you think!
